const UUIDs = {
	NAMES: {
		"0xFEFF": "GN Netcom",
		"0xFEFE": "GN ReSound A/S",
		"0xFEFD": "Gimbal, Inc.",
		"0xFEFC": "Gimbal, Inc.",
		"0xFEFB": "Telit Wireless Solutions (Formerly Stollmann E+V GmbH)",
		"0xFEFA": "PayPal, Inc.",
		"0xFEF9": "PayPal, Inc.",
		"0xFEF8": "Aplix Corporation",
		"0xFEF7": "Aplix Corporation",
		"0xFEF6": "Wicentric, Inc.",
		"0xFEF5": "Dialog Semiconductor GmbH",
		"0xFEF4": "Google",
		"0xFEF3": "Google",
		"0xFEF2": "CSR",
		"0xFEF1": "CSR",
		"0xFEF0": "Intel",
		"0xFEEF": "Polar Electro Oy",
		"0xFEEE": "Polar Electro Oy",
		"0xFEED": "Tile, Inc.",
		"0xFEEC": "Tile, Inc.",
		"0xFEEB": "Swirl Networks, Inc.",
		"0xFEEA": "Swirl Networks, Inc.",
		"0xFEE9": "Quintic Corp.",
		"0xFEE8": "Quintic Corp.",
		"0xFEE7": "Tencent Holdings Limited.",
		"0xFEE6": "Silvair, Inc.",
		"0xFEE5": "Nordic Semiconductor ASA",
		"0xFEE4": "Nordic Semiconductor ASA",
		"0xFEE3": "Anki, Inc.",
		"0xFEE2": "Anki, Inc.",
		"0xFEE1": "Anhui Huami Information Technology Co., Ltd.",
		"0xFEE0": "Anhui Huami Information Technology Co., Ltd.",
		"0xFEDF": "Design SHIFT",
		"0xFEDE": "Coin, Inc.",
		"0xFEDD": "Jawbone",
		"0xFEDC": "Jawbone",
		"0xFEDB": "Perka, Inc.",
		"0xFEDA": "ISSC Technologies Corp.",
		"0xFED9": "Pebble Technology Corporation",
		"0xFED8": "Google",
		"0xFED7": "Broadcom",
		"0xFED6": "Broadcom",
		"0xFED5": "Plantronics Inc.",
		"0xFED4": "Apple, Inc.",
		"0xFED3": "Apple, Inc.",
		"0xFED2": "Apple, Inc.",
		"0xFED1": "Apple, Inc.",
		"0xFED0": "Apple, Inc.",
		"0xFECF": "Apple, Inc.",
		"0xFECE": "Apple, Inc.",
		"0xFECD": "Apple, Inc.",
		"0xFECC": "Apple, Inc.",
		"0xFECB": "Apple, Inc.",
		"0xFECA": "Apple, Inc.",
		"0xFEC9": "Apple, Inc.",
		"0xFEC8": "Apple, Inc.",
		"0xFEC7": "Apple, Inc.",
		"0xFEC6": "Kocomojo, LLC",
		"0xFEC5": "Realtek Semiconductor Corp.",
		"0xFEC4": "PLUS Location Systems",
		"0xFEC3": "360fly, Inc.",
		"0xFEC2": "Blue Spark Technologies, Inc.",
		"0xFEC1": "KDDI Corporation",
		"0xFEC0": "KDDI Corporation",
		"0xFEBF": "Nod, Inc.",
		"0xFEBE": "Bose Corporation",
		"0xFEBD": "Clover Network, Inc",
		"0xFEBC": "Dexcom Inc",
		"0xFEBB": "adafruit industries",
		"0xFEBA": "Tencent Holdings Limited",
		"0xFEB9": "LG Electronics",
		"0xFEB8": "Facebook, Inc.",
		"0xFEB7": "Facebook, Inc.",
		"0xFEB6": "Vencer Co., Ltd",
		"0xFEB5": "WiSilica Inc.",
		"0xFEB4": "WiSilica Inc.",
		"0xFEB3": "Taobao",
		"0xFEB2": "Microsoft Corporation",
		"0xFEB1": "Electronics Tomorrow Limited",
		"0xFEB0": "Nest Labs Inc",
		"0xFEAF": "Nest Labs Inc",
		"0xFEAE": "Nokia",
		"0xFEAD": "Nokia",
		"0xFEAC": "Nokia",
		"0xFEAB": "Nokia",
		"0xFEAA": "Google",
		"0xFEA9": "Savant Systems LLC",
		"0xFEA8": "Savant Systems LLC",
		"0xFEA7": "UTC Fire and Security",
		"0xFEA6": "GoPro, Inc.",
		"0xFEA5": "GoPro, Inc.",
		"0xFEA4": "Paxton Access Ltd",
		"0xFEA3": "ITT Industries",
		"0xFEA2": "Intrepid Control Systems, Inc.",
		"0xFEA1": "Intrepid Control Systems, Inc.",
		"0xFEA0": "Google",
		"0xFE9F": "Google",
		"0xFE9E": "Dialog Semiconductor B.V.",
		"0xFE9D": "Mobiquity Networks Inc",
		"0xFE9C": "GSI Laboratories, Inc.",
		"0xFE9B": "Samsara Networks, Inc",
		"0xFE9A": "Estimote",
		"0xFE99": "Currant Inc",
		"0xFE98": "Currant Inc",
		"0xFE97": "Tesla Motors Inc.",
		"0xFE96": "Tesla Motors Inc.",
		"0xFE95": "Xiaomi Inc.",
		"0xFE94": "OttoQ In",
		"0xFE93": "OttoQ In",
		"0xFE92": "Jarden Safety & Security",
		"0xFE91": "Shanghai Imilab Technology Co.,Ltd",
		"0xFE90": "JUMA",
		"0xFE8F": "CSR",
		"0xFE8E": "ARM Ltd",
		"0xFE8D": "Interaxon Inc.",
		"0xFE8C": "TRON Forum",
		"0xFE8B": "Apple, Inc.",
		"0xFE8A": "Apple, Inc.",
		"0xFE89": "B&O Play A/S",
		"0xFE88": "SALTO SYSTEMS S.L.",
		"0xFE87": "青岛亿联客信息技术有限公司 )",
		"0xFE86": "HUAWEI Technologies Co., Ltd. ( 华为技术有限公司 )",
		"0xFE85": "RF Digital Corp",
		"0xFE84": "RF Digital Corp",
		"0xFE83": "Blue Bite",
		"0xFE82": "Medtronic Inc.",
		"0xFE81": "Medtronic Inc.",
		"0xFE80": "Doppler Lab",
		"0xFE7F": "Doppler Lab",
		"0xFE7E": "Awear Solutions Ltd",
		"0xFE7D": "Aterica Health Inc.",
		"0xFE7C": "Telit Wireless Solutions (Formerly Stollmann E+V GmbH)",
		"0xFE7B": "Orion Labs, Inc.",
		"0xFE7A": "Bragi GmbH",
		"0xFE79": "Zebra Technologies",
		"0xFE78": "Hewlett-Packard Company",
		"0xFE77": "Hewlett-Packard Company",
		"0xFE76": "TangoMe",
		"0xFE75": "TangoMe",
		"0xFE74": "unwire",
		"0xFE73": "Abbott (formerly St. Jude Medical, Inc.)",
		"0xFE72": "Abbott (formerly St. Jude Medical, Inc.)",
		"0xFE71": "Plume Design Inc",
		"0xFE70": "Beijing Jingdong Century Trading Co., Ltd.",
		"0xFE6F": "LINE Corporation",
		"0xFE6E": "The University of Tokyo",
		"0xFE6D": "The University of Tokyo",
		"0xFE6C": "TASER International, Inc.",
		"0xFE6B": "TASER International, Inc.",
		"0xFE6A": "Kontakt Micro-Location Sp. z o.o.",
		"0xFE69": "Qualcomm Life Inc",
		"0xFE68": "Qualcomm Life Inc",
		"0xFE67": "Lab Sensor Solutions",
		"0xFE66": "Intel Corporation",
		"0xFE65": "CHIPOLO d.o.o.",
		"0xFE64": "Siemens AG",
		"0xFE63": "Connected Yard, Inc.",
		"0xFE62": "Indagem Tech LLC",
		"0xFE61": "Logitech International SA",
		"0xFE60": "Lierda Science & Technology Group Co., Ltd.",
		"0xFE5F": "Eyefi, Inc.",
		"0xFE5E": "Plastc Corporation",
		"0xFE5D": "Grundfos A/S",
		"0xFE5C": "million hunters GmbH",
		"0xFE5B": "GT-tronics HK Ltd",
		"0xFE5A": "Cronologics Corporation",
		"0xFE59": "Nordic Semiconductor ASA",
		"0xFE58": "Nordic Semiconductor ASA",
		"0xFE57": "Dotted Labs",
		"0xFE56": "Google Inc.",
		"0xFE55": "Google Inc.",
		"0xFE54": "Motiv, Inc.",
		"0xFE53": "3M",
		"0xFE52": "SetPoint Medical",
		"0xFE51": "SRAM",
		"0xFE50": "Google Inc.",
		"0xFE4F": "Molekule, Inc.",
		"0xFE4E": "NTT docomo",
		"0xFE4D": "Casambi Technologies Oy",
		"0xFE4C": "Volkswagen AG",
		"0xFE4B": "Signify Netherlands B.V. (formerly Philips Lighting B.V.)",
		"0xFE4A": "OMRON HEALTHCARE Co., Ltd.",
		"0xFE49": "SenionLab AB",
		"0xFE48": "General Motors",
		"0xFE47": "General Motors",
		"0xFE46": "B&O Play A/S",
		"0xFE45": "Snapchat Inc",
		"0xFE44": "SK Telecom",
		"0xFE43": "Andreas Stihl AG & Co. KG",
		"0xFE42": "Nets A/S",
		"0xFE41": "Inugo Systems Limited",
		"0xFE40": "Inugo Systems Limited",
		"0xFE3F": "Friday Labs Limited",
		"0xFE3E": "BD Medical",
		"0xFE3D": "BD Medical",
		"0xFE3C": "alibaba",
		"0xFE3B": "Dolby Laboratories",
		"0xFE3A": "TTS Tooltechnic Systems AG & Co. KG",
		"0xFE39": "TTS Tooltechnic Systems AG & Co. KG",
		"0xFE38": "Spaceek LTD",
		"0xFE37": "Spaceek LTD",
		"0xFE36": "HUAWEI Technologies Co., Ltd",
		"0xFE35": "HUAWEI Technologies Co., Ltd",
		"0xFE34": "SmallLoop LLC",
		"0xFE33": "CHIPOLO d.o.o.",
		"0xFE32": "Pro-Mark, Inc.",
		"0xFE31": "Volkswagen AG",
		"0xFE30": "Volkswagen AG",
		"0xFE2F": "CRESCO Wireless, Inc",
		"0xFE2E": "ERi,Inc.",
		"0xFE2D": "SMART INNOVATION Co.,Ltd",
		"0xFE2C": "Google",
		"0xFE2B": "ITT Industries",
		"0xFE2A": "DaisyWorks, Inc.",
		"0xFE29": "Gibson Innovations",
		"0xFE28": "Ayla Networks",
		"0xFE27": "Google",
		"0xFE26": "Google",
		"0xFE25": "Apple, Inc.",
		"0xFE24": "August Home Inc",
		"0xFE23": "Zoll Medical Corporation",
		"0xFE22": "Zoll Medical Corporation",
		"0xFE21": "Bose Corporation",
		"0xFE20": "Emerson",
		"0xFE1F": "Garmin International, Inc.",
		"0xFE1E": "Smart Innovations Co., Ltd",
		"0xFE1D": "Illuminati Instrument Corporation",
		"0xFE1C": "NetMedia, Inc.",
		"0xFE1B": "Tyto Life LLC",
		"0xFE1A": "Tyto Life LLC",
		"0xFE19": "Google, Inc",
		"0xFE18": "Runtime, Inc.",
		"0xFE17": "Telit Wireless Solutions GmbH",
		"0xFE16": "Footmarks, Inc.",
		"0xFE15": "Amazon.com Services, Inc..",
		"0xFE14": "Flextronics International USA Inc.",
		"0xFE13": "Apple Inc.",
		"0xFE12": "M-Way Solutions GmbH",
		"0xFE11": "GMC-I Messtechnik GmbH",
		"0xFE10": "LAPIS Technology Co., Ltd.",
		"0xFE0F": "Signify Netherlands B.V. (formerly Philips Lighting B.V.)",
		"0xFE0E": "Setec Pty Ltd",
		"0xFE0D": "Procter & Gamble",
		"0xFE0C": "Procter & Gamble",
		"0xFE0B": "ruwido austria gmbh",
		"0xFE0A": "ruwido austria gmbh",
		"0xFE09": "Pillsy, Inc.",
		"0xFE08": "Microsoft",
		"0xFE07": "Sonos, Inc.",
		"0xFE06": "Qualcomm Technologies, Inc.",
		"0xFE05": "CORE Transport Technologies NZ Limited",
		"0xFE04": "OpenPath Security Inc",
		"0xFE03": "Amazon.com Services, Inc.",
		"0xFE02": "Robert Bosch GmbH",
		"0xFE01": "Duracell U.S. Operations Inc.",
		"0xFE00": "Amazon.com Services, Inc.",
		"0xFDFF": "OSRAM GmbH",
		"0xFDFE": "ADHERIUM(NZ) LIMITED",
		"0xFDFD": "RecursiveSoft Inc.",
		"0xFDFC": "Optrel AG",
		"0xFDFB": "Tandem Diabetes Care",
		"0xFDFA": "Tandem Diabetes Care",
		"0xFDF9": "INIA",
		"0xFDF8": "Onvocal",
		"0xFDF7": "HP Inc.",
		"0xFDF6": "AIAIAI ApS",
		"0xFDF5": "Milwaukee Electric Tools",
		"0xFDF4": "O. E. M. Controls, Inc.",
		"0xFDF3": "Amersports",
		"0xFDF2": "AMICCOM Electronics Corporation",
		"0xFDF1": "LAMPLIGHT Co.,Ltd",
		"0xFDF0": "Google Inc.",
		"0xFDEF": "ART AND PROGRAM, INC.",
		"0xFDEE": "Huawei Technologies Co., Ltd.",
		"0xFDED": "Pole Star",
		"0xFDEC": "Mannkind Corporation",
		"0xFDEB": "Syntronix Corporation",
		"0xFDEA": "SeeScan, Inc",
		"0xFDE9": "Spacesaver Corporation",
		"0xFDE8": "Robert Bosch GmbH",
		"0xFDE7": "SECOM Co., LTD",
		"0xFDE6": "Intelletto Technologies Inc",
		"0xFDE5": "SMK Corporation",
		"0xFDE4": "JUUL Labs, Inc.",
		"0xFDE3": "Abbott Diabetes Care",
		"0xFDE2": "Google Inc.",
		"0xFDE1": "Fortin Electronic Systems",
		"0xFDE0": "John Deere",
		"0xFDDF": "Harman International",
		"0xFDDE": "Noodle Technology Inc.",
		"0xFDDD": "Arch Systems Inc",
		"0xFDDC": "4iiii Innovations Inc.",
		"0xFDDB": "Samsung Electronics Co., Ltd.",
		"0xFDDA": "MHCS",
		"0xFDD9": "Jiangsu Teranovo Tech Co., Ltd.",
		"0xFDD8": "Jiangsu Teranovo Tech Co., Ltd.",
		"0xFDD7": "Emerson",
		"0xFDD6": "Ministry of Supply",
		"0xFDD5": "Brompton Bicycle Ltd",
		"0xFDD4": "LX Solutions Pty Limited",
		"0xFDD3": "FUBA Automotive Electronics GmbH",
		"0xFDD2": "Bose Corporation",
		"0xFDD1": "Huawei Technologies Co., Ltd",
		"0xFDD0": "Huawei Technologies Co., Ltd",
		"0xFDCF": "Nalu Medical, Inc",
		"0xFDCE": "SENNHEISER electronic GmbH & Co. KG",
		"0xFDCD": "Qingping Technology (Beijing) Co., Ltd.",
		"0xFDCC": "Shoof Technologies",
		"0xFDCB": "Meggitt SA",
		"0xFDCA": "Fortin Electronic Systems",
		"0xFDC9": "Busch-Jaeger Elektro GmbH",
		"0xFDC8": "Hach – Danaher",
		"0xFDC7": "Eli Lilly and Company",
		"0xFDC6": "Eli Lilly and Company",
		"0xFDC5": "Automatic Labs",
		"0xFDC4": "Simavita (Aust) Pty Ltd",
		"0xFDC3": "Baidu Online Network Technology (Beijing) Co., Ltd",
		"0xFDC2": "Baidu Online Network Technology (Beijing) Co., Ltd",
		"0xFDC1": "Hunter Douglas",
		"0xFDC0": "Hunter Douglas",
		"0xFDBF": "California Things Inc.",
		"0xFDBE": "California Things Inc.",
		"0xFDBD": "Clover Network, Inc.",
		"0xFDBC": "Emerson",
		"0xFDBB": "Profoto",
		"0xFDBA": "Comcast Cable Corporation",
		"0xFDB9": "Comcast Cable Corporation",
		"0xFDB8": "LivaNova USA Inc.",
		"0xFDB7": "LivaNova USA Inc.",
		"0xFDB6": "GWA Hygiene GmbH",
		"0xFDB5": "ECSG",
		"0xFDB4": "HP Inc",
		"0xFDB3": "Audiodo AB",
		"0xFDB2": "Portable Multimedia Ltd",
		"0xFDB1": "Proxy Technologies, Inc.",
		"0xFDB0": "Proxy Technologies, Inc.",
		"0xFDAF": "Wiliot LTD",
		"0xFDAE": "Houwa System Design, k.k.",
		"0xFDAD": "Houwa System Design, k.k.",
		"0xFDAC": "Tentacle Sync GmbH",
		"0xFDAB": "Xiaomi Inc.",
		"0xFDAA": "Xiaomi Inc.",
		"0xFDA9": "Rhombus Systems, Inc.",
		"0xFDA8": "PSA Peugeot Citroën",
		"0xFDA7": "WWZN Information Technology Company Limited",
		"0xFDA6": "WWZN Information Technology Company Limited",
		"0xFDA5": "Neurostim OAB, Inc.",
		"0xFDA4": "Inseego Corp.",
		"0xFDA3": "Inseego Corp.",
		"0xFDA2": "Groove X, Inc",
		"0xFDA1": "Groove X, Inc",
		"0xFDA0": "Secugen Corporation",
		"0xFD9F": "VitalTech Affiliates LLC",
		"0xFD9E": "The Coca-Cola Company",
		"0xFD9D": "Gastec Corporation",
		"0xFD9C": "Huawei Technologies Co., Ltd.",
		"0xFD9B": "Huawei Technologies Co., Ltd.",
		"0xFD9A": "Huawei Technologies Co., Ltd.",
		"0xFD99": "ABB Oy",
		"0xFD98": "Disney Worldwide Services, Inc.",
		"0xFD97": "June Life, Inc.",
		"0xFD96": "Google LLC",
		"0xFD95": "Rigado",
		"0xFD94": "Hewlett Packard Enterprise",
		"0xFD93": "Bayerische Motoren Werke AG",
		"0xFD92": "Qualcomm Technologies International, Ltd. (QTIL)",
		"0xFD91": "Groove X, Inc.",
		"0xFD90": "Guangzhou SuperSound Information Technology Co.,Ltd",
		"0xFD8F": "Matrix ComSec Pvt. Ltd.",
		"0xFD8E": "Motorola Solutions",
		"0xFD8D": "quip NYC Inc.",
		"0xFD8C": "Google LLC",
		"0xFD8B": "Jigowatts Inc.",
		"0xFD8A": "Signify Netherlands B.V.",
		"0xFD89": "Urbanminded LTD",
		"0xFD88": "Urbanminded LTD",
		"0xFD87": "Google LLC",
		"0xFD86": "Abbott",
		"0xFD85": "Husqvarna AB",
		"0xFD84": "Tile, Inc.",
		"0xFD83": "iNFORM Technology GmbH",
		"0xFD82": "Sony Corporation",
		"0xFD81": "CANDY HOUSE, Inc.",
		"0xFD80": "Phindex Technologies, Inc",
		"0xFD7F": "Husqvarna AB",
		"0xFD7E": "Samsung Electronics Co., Ltd.",
		"0xFD7D": "Center for Advanced Research Wernher Von Braun",
		"0xFD7C": "Toshiba Information Systems(Japan) Corporation",
		"0xFD7B": "WYZE LABS, INC.",
		"0xFD7A": "Withings",
		"0xFD79": "Withings",
		"0xFD78": "Withings",
		"0xFD77": "Withings",
		"0xFD76": "Insulet Corporation",
		"0xFD75": "Insulet Corporation",
		"0xFD74": "BRControls Products BV",
		"0xFD73": "BRControls Products BV",
		"0xFD72": "Logitech International SA",
		"0xFD71": "GN Hearing A/S",
		"0xFD70": "GuangDong Oppo Mobile Telecommunications Corp., Ltd",
		"0xFD6F": "Apple, Inc.",
		"0xFD6E": "Polidea sp. z o.o.",
		"0xFD6D": "Sigma Elektro GmbH",
		"0xFD6C": "Samsung Electronics Co., Ltd.",
		"0xFD6B": "rapitag GmbH",
		"0xFD6A": "Emerson",
		"0xFD69": "Samsung Electronics Co., Ltd",
		"0xFD68": "Ubique Innovation AG",
		"0xFD67": "Montblanc Simplo GmbH",
		"0xFD66": "Zebra Technologies Corporation",
		"0xFD65": "Razer Inc.",
		"0xFD64": "INRIA",
		"0xFD63": "Fitbit, Inc.",
		"0xFD62": "Fitbit, Inc.",
		"0xFD61": "Arendi AG",
		"0xFD60": "Sercomm Corporation",
		"0xFD5F": "Oculus VR, LLC",
		"0xFD5E": "Tapkey GmbH",
		"0xFD5D": "maxon motor ltd.",
		"0xFD5C": "React Mobile",
		"0xFD5B": "V2SOFT INC.",
		"0xFD5A": "Samsung Electronics Co., Ltd.",
		"0xFD59": "Samsung Electronics Co., Ltd.",
		"0xFD58": "Volvo Car Corporation",
		"0xFD57": "Volvo Car Corporation",
		"0xFD56": "Resmed Ltd",
		"0xFD55": "Braveheart Wireless, Inc.",
		"0xFD54": "Qingdao Haier Technology Co., Ltd.",
		"0xFD53": "PCI Private Limited",
		"0xFD52": "UTC Fire and Security",
		"0xFD51": "UTC Fire and Security",
		"0xFD50": "Hangzhou Tuya Information Technology Co., Ltd",
		"0xFD4F": "Forkbeard Technologies AS",
		"0xFD4E": "70mai Co.,Ltd.",
		"0xFD4D": "70mai Co.,Ltd.",
		"0xFD4C": "Adolf Wuerth GmbH & Co KG",
		"0xFD4B": "Samsung Electronics Co., Ltd.",
		"0xFD4A": "Sigma Elektro GmbH",
		"0xFD49": "Panasonic Corporation",
		"0xFD48": "Geberit International AG",
		"0xFD47": "Liberty Global Inc.",
		"0xFD46": "Lemco IKE",
		"0xFD45": "GB Solution co.,Ltd",
		"0xFD44": "Apple Inc.",
		"0xFD43": "Apple Inc.",
		"0xFD42": "Globe (Jiangsu) Co.,Ltd",
		"0xFD41": "Amazon Lab126",
		"0xFD40": "Beflex Inc.",
		"0xFD3F": "Cognosos, Inc",
		"0xFD3E": "Pure Watercraft, inc.",
		"0xFD3D": "Woan Technology (Shenzhen) Co., Ltd.",
		"0xFD3C": "Redline Communications Inc.",
		"0xFD3B": "Verkada Inc.",
		"0xFD3A": "Verkada Inc.",
		"0xFD39": "PREDIKTAS",
		"0xFD38": "Danfoss A/S",
		"0xFD37": "TireCheck GmbH",
		"0xFD36": "Google LLC",
		"0xFD35": "Transsion Holdings Limited",
		"0xFD34": "Aerosens LLC.",
		"0xFD33": "DashLogic, Inc.",
		"0xFD32": "Gemalto Holding BV",
		"0xFD31": "LG Electronics Inc.",
		"0xFD30": "Sesam Solutions BV",
		"0xFD2F": "Bitstrata Systems Inc.",
		"0xFD2E": "Bitstrata Systems Inc.",
		"0xFD2D": "Xiaomi Inc.",
		"0xFD2C": "The Access Technologies",
		"0xFD2B": "The Access Technologies",
		"0xFD2A": "Sony Corporation",
		"0xFD29": "Asahi Kasei Corporation",
		"0xFD28": "Julius Blum GmbH",
		"0xFD27": "i2Systems",
		"0xFD26": "Novo Nordisk A/S",
		"0xFD25": "GD Midea Air-Conditioning Equipment Co., Ltd.",
		"0xFD24": "GD Midea Air-Conditioning Equipment Co., Ltd.",
		"0xFD23": "DOM Sicherheitstechnik GmbH & Co. KG",
		"0xFD22": "Huawei Technologies Co., Ltd.",
		"0xFD21": "Huawei Technologies Co., Ltd.",
		"0xFD20": "GN Hearing A/S",
		"0xFD1F": "3M",
	},
	CHARACTERISTICS: {
		"0x2A00": "Device Name",
		"0x2A01": "Appearance",
		"0x2A02": "Peripheral Privacy Flag",
		"0x2A03": "Reconnection Address",
		"0x2A04": "Peripheral Preferred Connection Parameters",
		"0x2A05": "Service Changed",
		"0x2A06": "Alert Level",
		"0x2A07": "Tx Power Level",
		"0x2A08": "Date Time",
		"0x2A09": "Day of Week",
		"0x2A0A": "Day Date Time",
		"0x2A0C": "Exact Time 256",
		"0x2A0D": "DST Offset",
		"0x2A0E": "Time Zone",
		"0x2A0F": "Local Time Information",
		"0x2A11": "Time with DST",
		"0x2A12": "Time Accuracy",
		"0x2A13": "Time Source",
		"0x2A14": "Reference Time Information",
		"0x2A16": "Time Update Control Point",
		"0x2A17": "Time Update State",
		"0x2A18": "Glucose Measurement",
		"0x2A19": "Battery Level",
		"0x2A1C": "Temperature Measurement",
		"0x2A1D": "Temperature Type",
		"0x2A1E": "Intermediate Temperature",
		"0x2A21": "Measurement Interval",
		"0x2A22": "Boot Keyboard Input Report",
		"0x2A23": "System ID",
		"0x2A24": "Model Number String",
		"0x2A25": "Serial Number String",
		"0x2A26": "Firmware Revision String",
		"0x2A27": "Hardware Revision String",
		"0x2A28": "Software Revision String",
		"0x2A29": "Manufacturer Name String",
		"0x2A2A": "IEEE 11073-20601 Regulatory Certification Data List",
		"0x2A2B": "Current Time",
		"0x2A31": "Scan Refresh",
		"0x2A32": "Boot Keyboard Output Report",
		"0x2A33": "Boot Mouse Input Report",
		"0x2A34": "Glucose Measurement Context",
		"0x2A35": "Blood Pressure Measurement",
		"0x2A36": "Intermediate Cuff Pressure",
		"0x2A37": "Heart Rate Measurement",
		"0x2A38": "Body Sensor Location",
		"0x2A39": "Heart Rate Control Point",
		"0x2A3F": "Alert Status",
		"0x2A40": "Ringer Control Point",
		"0x2A41": "Ringer Setting",
		"0x2A42": "Alert Category ID Bit Mask",
		"0x2A43": "Alert Category ID",
		"0x2A44": "Alert Notification Control Point",
		"0x2A45": "Unread Alert Status",
		"0x2A46": "New Alert",
		"0x2A47": "Supported New Alert Category",
		"0x2A48": "Supported Unread Alert Category",
		"0x2A49": "Blood Pressure Feature",
		"0x2A4A": "HID Information",
		"0x2A4B": "Report Map",
		"0x2A4C": "HID Control Point",
		"0x2A4D": "Report",
		"0x2A4E": "Protocol Mode",
		"0x2A4F": "Scan Interval Window",
		"0x2A50": "PnP ID",
		"0x2A51": "Glucose Feature",
		"0x2A52": "Record Access Control Point",
		"0x2A53": "RSC Measurement",
		"0x2A54": "RSC Feature",
		"0x2A55": "SC Control Point",
		"0x2A5A": "Aggregate",
		"0x2A5B": "CSC Measurement",
		"0x2A5C": "CSC Feature",
		"0x2A5D": "Sensor Location",
		"0x2A5E": "PLX Spot-Check Measurement",
		"0x2A5F": "PLX Continuous Measurement",
		"0x2A60": "PLX Features",
		"0x2A63": "Cycling Power Measurement",
		"0x2A64": "Cycling Power Vector",
		"0x2A65": "Cycling Power Feature",
		"0x2A66": "Cycling Power Control Point",
		"0x2A67": "Location and Speed",
		"0x2A68": "Navigation",
		"0x2A69": "Position Quality",
		"0x2A6A": "LN Feature",
		"0x2A6B": "LN Control Point",
		"0x2A6C": "Elevation",
		"0x2A6D": "Pressure",
		"0x2A6E": "Temperature",
		"0x2A6F": "Humidity",
		"0x2A70": "True Wind Speed",
		"0x2A71": "True Wind Direction",
		"0x2A72": "Apparent Wind Speed",
		"0x2A73": "Apparent Wind Direction",
		"0x2A74": "Gust Factor",
		"0x2A75": "Pollen Concentration",
		"0x2A76": "UV Index",
		"0x2A77": "Irradiance",
		"0x2A78": "Rainfall",
		"0x2A79": "Wind Chill",
		"0x2A7A": "Heat Index",
		"0x2A7B": "Dew Point",
		"0x2A7D": "Descriptor Value Changed",
		"0x2A7E": "Aerobic Heart Rate Lower Limit",
		"0x2A7F": "Aerobic Threshold",
		"0x2A80": "Age",
		"0x2A81": "Anaerobic Heart Rate Lower Limit",
		"0x2A82": "Anaerobic Heart Rate Upper Limit",
		"0x2A83": "Anaerobic Threshold",
		"0x2A84": "Aerobic Heart Rate Upper Limit",
		"0x2A85": "Date of Birth",
		"0x2A86": "Date of Threshold Assessment",
		"0x2A87": "Email Address",
		"0x2A88": "Fat Burn Heart Rate Lower Limit",
		"0x2A89": "Fat Burn Heart Rate Upper Limit",
		"0x2A8A": "First Name",
		"0x2A8B": "Five Zone Heart Rate Limits",
		"0x2A8C": "Gender",
		"0x2A8D": "Heart Rate Max",
		"0x2A8E": "Height",
		"0x2A8F": "Hip Circumference",
		"0x2A90": "Last Name",
		"0x2A91": "Maximum Recommended Heart Rate",
		"0x2A92": "Resting Heart Rate",
		"0x2A93": "Sport Type for Aerobic and Anaerobic Thresholds",
		"0x2A94": "Three Zone Heart Rate Limits",
		"0x2A95": "Two Zone Heart Rate Limits",
		"0x2A96": "VO2 Max",
		"0x2A97": "Waist Circumference",
		"0x2A98": "Weight",
		"0x2A99": "Database Change Increment",
		"0x2A9A": "User Index",
		"0x2A9B": "Body Composition Feature",
		"0x2A9C": "Body Composition Measurement",
		"0x2A9D": "Weight Measurement",
		"0x2A9E": "Weight Scale Feature",
		"0x2A9F": "User Control Point",
		"0x2AA0": "Magnetic Flux Density - 2D",
		"0x2AA1": "Magnetic Flux Density - 3D",
		"0x2AA2": "Language",
		"0x2AA3": "Barometric Pressure Trend",
		"0x2AA4": "Bond Management Control Point",
		"0x2AA5": "Bond Management Feature",
		"0x2AA6": "Central Address Resolution",
		"0x2AA7": "CGM Measurement",
		"0x2AA8": "CGM Feature",
		"0x2AA9": "CGM Status",
		"0x2AAA": "CGM Session Start Time",
		"0x2AAB": "CGM Session Run Time",
		"0x2AAC": "CGM Specific Ops Control Point",
		"0x2AAD": "Indoor Positioning Configuration",
		"0x2AAE": "Latitude",
		"0x2AAF": "Longitude",
		"0x2AB0": "Local North Coordinate",
		"0x2AB1": "Local East Coordinate",
		"0x2AB2": "Floor Number",
		"0x2AB3": "Altitude",
		"0x2AB4": "Uncertainty",
		"0x2AB5": "Location Name",
		"0x2AB6": "URI",
		"0x2AB7": "HTTP Headers",
		"0x2AB8": "HTTP Status Code",
		"0x2AB9": "HTTP Entity Body",
		"0x2ABA": "HTTP Control Point",
		"0x2ABB": "HTTPS Security",
		"0x2ABC": "TDS Control Point",
		"0x2ABD": "OTS Feature",
		"0x2ABE": "object name",
		"0x2ABF": "object type",
		"0x2AC0": "object size",
		"0x2AC1": "object first created",
		"0x2AC2": "object last modified",
		"0x2AC3": "object ID",
		"0x2AC4": "object properties",
		"0x2AC5": "object actioncontrol point",
		"0x2AC6": "object list control point",
		"0x2AC7": "object list filter",
		"0x2AC8": "object changed",
		"0x2AC9": "Resolvable Private Address Only",
		"0x2ACA": "Unspecified",
		"0x2ACB": "Directory Listing",
		"0x2ACC": "Fitness Machine Feature",
		"0x2ACD": "Treadmill Data",
		"0x2ACE": "Cross Trainer Data",
		"0x2ACF": "Step Climber Data",
		"0x2AD0": "Stair Climber Data",
		"0x2AD1": "Rower Data",
		"0x2AD2": "Indoor Bike Data",
		"0x2AD3": "Training Status",
		"0x2AD4": "Supported Speed Range",
		"0x2AD5": "Supported Inclination Range",
		"0x2AD6": "Supported Resistance Level Range",
		"0x2AD7": "Supported Heart Rate Range",
		"0x2AD8": "Supported Power Range",
		"0x2AD9": "Fitness Machine Control Point",
		"0x2ADA": "Fitness Machine Status",
		"0x2ADB": "Mesh Provisioning Data In",
		"0X2ADC": "Mesh Provisioning Data Out",
		"0X2ADD": "Mesh Proxy Data In",
		"0X2ADE": "Mesh Proxy Data Out",
		"0X2AE0": "Average Current",
		"0X2AE1": "Average Voltage",
		"0X2AE2": "Boolean",
		"0X2AE3": "Chromatic Distance From Planckian",
		"0X2AE4": "Chromaticity Coordinates",
		"0X2AE5": "Chromaticity in CCT And Duv Values",
		"0X2AE6": "Chromaticity Tolerance",
		"0X2AE7": "CIE 13.3-1995 Color Rendering Index",
		"0X2AE8": "Coefficient",
		"0X2AE9": "Correlated Color Temperature",
		"0X2AEA": "Count 16",
		"0X2AEB": "Count 24",
		"0X2AEC": "Country Code",
		"0X2AED": "Date UTC",
		"0X2AEE": "Electric Current",
		"0X2AEF": "Electric Current Range",
		"0X2AF0": "Electric Current Specification",
		"0X2AF1": "Electric Current Statistics",
		"0X2AF2": "Energy",
		"0X2AF3": "Energy In A Period Of Day",
		"0X2AF4": "Event Statistics",
		"0X2AF5": "Fixed String 16",
		"0X2AF6": "Fixed String 24",
		"0X2AF7": "Fixed String 36",
		"0X2AF8": "Fixed String 8",
		"0X2AF9": "Generic Level",
		"0X2AFA": "Global Trade Item Number",
		"0X2AFB": "Illuminance",
		"0X2AFC": "Luminous Efficacy",
		"0X2AFD": "Luminous Energy",
		"0X2AFE": "Luminous Exposure",
		"0X2AFF": "Luminous Flux",
		"0x2B00": "Luminous Flux Range",
		"0x2B01": "Luminous Intensity",
		"0x2B02": "Mass Flow",
		"0x2B03": "Perceived Lightness",
		"0x2B04": "Percentage 8",
		"0x2B05": "Power",
		"0x2B06": "Power Specification",
		"0x2B07": "Relative Runtime In A Current Range",
		"0x2B08": "Relative Runtime In A Generic Level Range",
		"0x2B09": "Relative Value In A Voltage Range",
		"0x2B0A": "Relative Value In An Illuminance Range",
		"0x2B0B": "Relative Value In A Period Of Day",
		"0x2B0C": "Relative Value In A Temperature Range",
		"0x2B0D": "Temperature 8",
		"0x2B0E": "Temperature 8 In A Period Of Day",
		"0x2B0F": "Temperature 8 Statistics",
		"0x2B10": "Temperature Range",
		"0x2B11": "Temperature Statistics",
		"0x2B12": "Time Decihour 8",
		"0x2B13": "Time Exponential 8",
		"0x2B14": "Time Hour 24",
		"0x2B15": "Time Millisecond 24",
		"0x2B16": "Time Second 16",
		"0x2B17": "Time Second 8",
		"0x2B18": "Voltage",
		"0x2B19": "Voltage Specification",
		"0x2B1A": "Voltage Statistics",
		"0x2B1B": "Volume Flow",
		"0x2B1C": "Chromaticity Coordinate",
		"0x2B1D": "RC Feature",
		"0x2B1E": "RC Settings",
		"0x2B1F": "Reconnection Configuration Control Point",
		"0x2B20": "IDD Status Changed",
		"0x2B21": "IDD Status",
		"0x2B22": "IDD Annunciation Status",
		"0x2B23": "IDD Features",
		"0x2B24": "IDD Status Reader Control Point",
		"0x2B25": "IDD Command Control Point",
		"0x2B26": "IDD Command Data",
		"0x2B27": "IDD Record Access Control Point",
		"0x2B28": "IDD History Data",
		"0x2B29": "Client Supported Features",
		"0x2B2A": "Database Hash",
		"0x2B2B": "BSS Control Point",
		"0x2B2C": "BSS Response",
		"0x2B2D": "Emergency ID",
		"0x2B2E": "Emergency Text",
		"0x2B34": "Enhanced Blood Pressure Measurement",
		"0x2B35": "Enhanced Intermediate Cuff Pressure",
		"0x2B36": "Blood Pressure Record",
		"0x2B38": "BR-EDR Handover Data",
		"0x2B39": "Bluetooth SIG Data",
		"0x2B3A": "Server Supported Features",
		"0x2B3B": "Physical Activity Monitor Features",
		"0x2B3C": "General Activity Instantaneous Data",
		"0x2B3D": "General Activity Summary Data",
		"0x2B3E": "CardioRespiratory Activity Instantaneous Data",
		"0x2B3F": "CardioRespiratory Activity Summary Data",
		"0x2B40": "Step Counter Activity Summary Data",
		"0x2B41": "Sleep Activity Instantaneous Data",
		"0x2B42": "Sleep Activity Summary Data",
		"0x2B43": "Physical Activity Monitor Control Point",
		"0x2B44": "Current Session",
		"0x2B45": "Session",
		"0x2B46": "Preferred Units",
		"0x2B47": "High Resolution Height",
		"0x2B48": "Middle Name",
		"0x2B49": "Stride Length",
		"0x2B4A": "Handedness",
		"0x2B4B": "Device Wearing Position",
		"0x2B4C": "Four Zone Heart Rate Limits",
		"0x2B4D": "High Intensity Exercise Threshold",
		"0x2B4E": "Activity Goal",
		"0x2B4F": "Sedentary Interval Notification",
		"0x2B50": "Caloric Intake",
		"0x2B77": "Audio Input State",
		"0x2B78": "Gain Settings Attribute",
		"0x2B79": "Audio Input Type",
		"0x2B7A": "Audio Input Status",
		"0x2B7B": "Audio Input Control Point",
		"0x2B7C": "Audio Input Description",
		"0x2B7D": "Volume State",
		"0x2B7E": "Volume Control Point",
		"0x2B7F": "Volume Flags",
		"0x2B80": "Offset State",
		"0x2B81": "Audio Location",
		"0x2B82": "Volume Offset Control Point",
		"0x2B83": "Audio Output Description",
		"0x2B84": "Set Identity Resolving Key Characteristic",
		"0x2B85": "Size Characteristic",
		"0x2B86": "Lock Characteristic",
		"0x2B87": "Rank Characteristic",
		"0x2B8E": "Device Time Feature",
		"0x2B8F": "Device Time Parameters",
		"0x2B90": "Device Time",
		"0x2B91": "Device Time Control Point",
		"0x2B92": "Time Change Log Data",
		"0x2B93": "Media Player Name",
		"0x2B94": "Media Player Icon Object ID",
		"0x2B95": "Media Player Icon URL",
		"0x2B96": "Track Changed",
		"0x2B97": "Track Title",
		"0x2B98": "Track Duration",
		"0x2B99": "Track Position",
		"0x2B9A": "Playback Speed",
		"0x2B9B": "Seeking Speed",
		"0x2B9C": "Current Track Segments Object ID",
		"0x2B9D": "Current Track Object ID",
		"0x2B9E": "Next Track Object ID",
		"0x2B9F": "Parent Group Object ID",
		"0x2BA0": "Current Group Object ID",
		"0x2BA1": "Playing Order",
		"0x2BA2": "Playing Orders Supported",
		"0x2BA3": "Media State",
		"0x2BA4": "Media Control Point",
		"0x2BA5": "Media Control Point Opcodes Supported",
		"0x2BA6": "Search Results Object ID",
		"0x2BA7": "Search Control Point",
		"0x2BA9": "Media Player Icon Object Type",
		"0x2BAA": "Track Segments Object Type",
		"0x2BAB": "Track Object Type",
		"0x2BAC": "Group Object Type",
		"0x2BAD": "Constant Tone Extension Enable",
		"0x2BAE": "Advertising Constant Tone Extension Minimum Length",
		"0x2BAF": "Advertising Constant Tone Extension Minimum Transmit Count",
		"0x2BB0": "Advertising Constant Tone Extension Transmit Duration",
		"0x2BB1": "Advertising Constant Tone Extension Interval",
		"0x2BB2": "Advertising Constant Tone Extension PHY",
		"0x2BB3": "Bearer Provider Name",
		"0x2BB4": "Bearer UCI",
		"0x2BB5": "Bearer Technology",
		"0x2BB6": "Bearer URI Schemes Supported List",
		"0x2BB7": "Bearer Signal Strength",
		"0x2BB8": "Bearer Signal Strength Reporting Interval",
		"0x2BB9": "Bearer List Current Calls",
		"0x2BBA": "Content Control ID",
		"0x2BBB": "Status Flags",
		"0x2BBC": "Incoming Call Target Bearer URI",
		"0x2BBD": "Call State",
		"0x2BBE": "Call Control Point",
		"0x2BBF": "Call Control Point Optional Opcodes",
		"0x2BC0": "Termination Reason",
		"0x2BC1": "Incoming Call",
		"0x2BC2": "Call Friendly Name",
		"0x2BC3": "Mute",
	}
}

const MESSAGE_TYPES = {
	UPDATE_ANIMATION: "a:",
	UPDATE_BRIGHTNESS: "b:",
	UPDATE_COLOR: "c:",
	DEBUG_MESSAGE: "d:",
}

export default {
	MESSAGE_TYPES,
	UUIDs,
}